/**
 * NextAuth Route Handlers
 * ------------------------------------------------------------------
 * Re-exports HTTP handlers generated by NextAuth.
 *
 * Purpose:
 * - Wires NextAuth into the Next.js App Router
 * - Exposes GET and POST handlers required for authentication flows
 *
 * Notes:
 * - These handlers support sign-in, sign-out, callbacks,
 *   session retrieval, and provider redirects
 * - This file should live under the appropriate route segment
 *   (e.g. /app/api/auth/[...nextauth]/route.ts)
 */

import { handlers } from "@/auth";

/**
 * Export GET and POST handlers for the App Router.
 * NextAuth internally routes requests based on method and path.
 */
export const { GET, POST } = handlers;
